Description: >
    This template deploys a Lambda function that will cofigure the required programs to to be able to manage the hosts of a working Solodev cluster.

Parameters:

    EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String

    AutoScalingGroup:
      Description: The AutoScalingGroup that the EC2 cluster is deployed to
      Type: String

    KeyName:
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
      Type: String

    InstanceUser:
      Type: String
      Default: 'solodev-user'
      Description: Name of admin user for instance (solodev-user for example)

    FQDN:
      Type: String
      Description: Fully qualified URL for using app.  DNS of FQDN must be pointed to CNAME of ALB.

    SolodevBucket:
      Type: String
      Description: A reference to the S3 bucket for solodev

    DatabaseHost:
      Type: String
      Description: The database host

    DatabaseName:
      Type: String
      Description: The database name

    DatabaseUsername:
      Type: String
      Description: The database user name

    DatabasePassword:
      Type: String
      Description: The database user password

    MongoHost:
      Type: String
      Description: The mongo host

    LambdaExecutionRole:
      Type: String
      Description: A reference to the lambda execution role
    
Resources:

  InstanceTerminatingHook:
    Type: 'AWS::AutoScaling::LifecycleHook'
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DefaultResult: ABANDON
      HeartbeatTimeout: '900'
      LifecycleTransition: 'autoscaling:EC2_INSTANCE_TERMINATING'
      NotificationTargetARN: !Ref NotificationTopic
      RoleARN: !GetAtt 
        - AutoscalingNotificationRole
        - Arn
    DependsOn: NotificationTopic

  InstanceActivatingHook:
    Type: 'AWS::AutoScaling::LifecycleHook'
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DefaultResult: CONTINUE
      HeartbeatTimeout: '900'
      LifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
      NotificationTargetARN: !Ref NotificationTopic
      RoleARN: !GetAtt 
        - AutoscalingNotificationRole
        - Arn
    DependsOn: NotificationTopic

  AutoscalingNotificationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - autoscaling.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole'

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LifecycleExecuteSolodev
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      SourceArn: !Ref NotificationTopic

  LifecycleExecuteSolodev:
    Type: 'AWS::Lambda::Function'
    Properties:
      Environment:
        Variables:
          cluster: !Ref AutoScalingGroup
          instance_user: !Ref InstanceUser
          bucket:  !Ref SolodevBucket
          FQDN: !Ref FQDN
          database_name: !Ref DatabaseName
          database_host: !Ref DatabaseHost
          database_user: !Ref DatabaseUsername
          database_password: !Ref DatabasePassword
          mongo_host: !Ref MongoHost
      Handler: solodev.run
      Role: !Ref LambdaExecutionRole
      Code: 
        S3Bucket: !Ref SolodevBucket
        S3Key: 'solodev-runner.zip'
      Runtime: python3.6
      Timeout: 300

  ExecuteLifecycleExecuteSolodev:
    Type: 'Custom::ExecuteLifecycleExecuteSolodev'
    Properties:
      ServiceToken: !GetAtt LifecycleExecuteSolodev.Arn
      Region: !Ref 'AWS::Region'

  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - 
          Endpoint: !GetAtt 
            - LifecycleExecuteSolodev
            - Arn
          Protocol: lambda
    DependsOn: ExecuteLifecycleExecuteSolodev