Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Setup"
        Parameters: 
          - VPCID
          - Subnets
          - InstanceType
          - InstanceCount
          - KeyName
      - 
        Label: 
          default: "CMS Settings"
        Parameters: 
            - AdminUser
            - AdminPassword
            - DatabaseName
            - DatabaseUsername
            - DatabasePassword
            - StorageEncrypted
      - 
        Label: 
          default: "Optional: SSL Configuration"
        Parameters: 
          - FQDN
          - CertificateArn
      - 
        Label: 
          default: "Optional: Advanced"
        Parameters: 
          - RestoreBucketName
          - AMI
          - Subscription
          - HostVolumeSize
          - SSHFrom
          - DeletionPolicy
      - 
        Label: 
          default: "Optional: Private Access (Required if not purchased through AWS)"
        Parameters: 
          - SolodevContainer
          - ApacheContainer
          - DockerUsername
          - DockerPassword
          - DockerEmail

Parameters:

    VPCID: 
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Application should be deployed to
        AllowedPattern: .+
        ConstraintDescription: Please choose VPC

    Subnets:
        Description: Choose at least two public subnets for this application
        Type: List<AWS::EC2::Subnet::Id>
        AllowedPattern: .+
        ConstraintDescription: Please choose Subnets

    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        Type: 'AWS::EC2::KeyPair::KeyName'
        AllowedPattern: .+
        ConstraintDescription: Please choose EC2 KeyPair

    InstanceType:
        Type: String
        Default: m3.medium
        AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
        m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
        c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
        r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
        ConstraintDescription: Please choose a valid instance type.

#Enterprise Only
    InstanceCount:
        Description: 'Number of instances behind load balancer.  Minimum 2 required for high availability.'
        Default: 2
        AllowedValues: [1, 2, 3, 4, 5]
        Type: Number

    AMI:
        Description: 'Experimental: Build AMI (Please leave this blank unless told otherwise)'
        Default: ''
        Type: String

    DeletionPolicy:
        Default: 'Delete'
        Type: String
        Description: 'Experimental: Deletion Policy (Retain, Delete, Snapshot)'

#Lite Only - Do not use for other editions
    HostVolumeSize:
        Description: Size in GB of root volume
        Type: String
        Default: '128'
        AllowedValues:
        - '8'
        - '16'
        - '32'
        - '64'
        - '128'
        - '256'
        - '512'
        - '1024'
        - '2048'
        - '4096'

    SSHFrom:
        Description: Lockdown SSH access to the host
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.

#PRO & Enterprise Edition

    FQDN:
        Type: String
        Description: URL for app. FQDN must be pointed to CNAME of ALB.

    CertificateArn:
        Type: String
        Description: CertificateArn for SSL cert that matches the FQDN above. Please visit the AWS Certificate Manager.

    AdminUser:
        Description: The solodev admin username
        Type: String
        Default: 'solodev'
        AllowedPattern: .+
        ConstraintDescription: Please set admin username

    AdminPassword:
        NoEcho: true
        Description: The solodev admin password
        Type: String
        MinLength: 1
        MaxLength: 41
        AllowedPattern: .+
        ConstraintDescription: Please set admin password

    DatabaseName:
        Type: String
        Description: The database name
        Default: "solodev"

    DatabaseUsername:
        Description: Database root user
        Type: String
        Default: 'root'

    DatabasePassword:
        NoEcho: true
        Description: The database root password
        Type: String
        MinLength: 1
        MaxLength: 41
        AllowedPattern: .+
        ConstraintDescription: Please set database root password

    RestoreBucketName:
        Description: Name of S3 bucket containing files for restore
        Type: String
        Default: ""

#Pro + Enterprise
    StorageEncrypted:
        Default: 'true'
        Description: Enable encryption for both Database (RDS) and Filesystem (EFS)
        Type: String
        AllowedValues:
        - 'true'
        - 'false'
        ConstraintDescription: must be either true or false.

    Subscription:
        Default: 'Marketplace'
        Description: Select source of Solodev subscription
        Type: String
        AllowedValues:
        - 'Marketplace'
        - 'BYOL'
        ConstraintDescription: must be either Marketplace or BYOL.

#Docker Edition
    SolodevContainer:
        Description: Solodev container image
        Default: 'solodev/cms:latest'
        Type: String

    ApacheContainer:
        Description: Apache container image
        Default: 'solodev/cms-apache:latest'
        Type: String

#Docker Dev
    DockerUsername:
        Description: Docker username
        Type: String

    DockerPassword:
        NoEcho: true
        Description: Docker password
        Type: String

    DockerEmail:
        Description: Docker email address
        Type: String